// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizaAE.Infrastructure;

namespace OrganizaAE.Migrations
{
    [DbContext(typeof(OrganizaAeDbContext))]
    [Migration("20220104025207_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrganizaAE.Models.Mounth.Mount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("Mounths");
                });

            modelBuilder.Entity("OrganizaAE.Models.Payment.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdMounth")
                        .HasColumnType("int");

                    b.Property<int>("IdSocial")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OrganizaAE.Models.Social.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("Socials");
                });

            modelBuilder.Entity("OrganizaAE.Models.Mounth.Mount", b =>
                {
                    b.HasOne("OrganizaAE.Models.Payment.Payment", null)
                        .WithMany("Mounth")
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("OrganizaAE.Models.Social.Social", b =>
                {
                    b.HasOne("OrganizaAE.Models.Payment.Payment", null)
                        .WithMany("Social")
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("OrganizaAE.Models.Payment.Payment", b =>
                {
                    b.Navigation("Mounth");

                    b.Navigation("Social");
                });
#pragma warning restore 612, 618
        }
    }
}
